import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>SOOMIN's PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dev.png" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </Layout>
  );
}
