import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import Main from "./main";
import About from "./about";
import Education from "./education";
import Projects from "./projects";
import Skills from "./skills";
import Contacts from "./contacts";
import { TOKEN, DATABASE_ID } from "../config";

export default function Home({ results }) {
  return (
    <Layout>
      <Head>
        <title>SOOMIN`s PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dev.png" />
      </Head>
      <div>
        <Main />
        <About />
        <Skills />
        <Education />
        <Projects results={results} />
        <Contacts />
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Notion-Version": "2022-02-22",
      "Content-Type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({ page_size: 100 }),
  };

  console.log("test!!!");

  const response = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );

  const projects = await response.json();
  const results = projects.results;

  return {
    props: { results }, // will be passed to the page component as props
  };
}
