import Head from "next/head";
import Layout from "../components/layout";
import Main from "./main";
import About from "./about";
import Education from "./education";
import Projects from "./projects";
import Skills from "./skills";
import Contacts from "./contacts";
import { TOKEN, DATABASE_ID } from "../config";

export default function Home({ projects }) {
  console.log(projects);

  return (
    <Layout>
      <Head>
        <title>SOOMIN`s PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dev.png" />
      </Head>
      <div>
        <Main />
        <About />
        <Skills />
        <Education />
        <Projects projects={projects} />
        <Contacts />
      </div>
    </Layout>
  );
}

export async function getServerSideProps() {
  const options = {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Notion-Version": "2022-02-22",
      "Content-Type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      sorts: [
        {
          property: "Name",
          direction: "ascending",
        },
      ],
      page_size: 100,
    }),
  };

  const response = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );
  let projects = null;
  projects = await response.json();

  return {
    props: { projects }, // will be passed to the page component as props
  };
}
